2024-05-14 14:36:16,174 INFO    StreamThr :930393 [internal.py:wandb_internal():86] W&B internal server running at pid: 930393, started at: 2024-05-14 14:36:16.173646
2024-05-14 14:36:16,175 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status
2024-05-14 14:36:16,178 INFO    WriterThread:930393 [datastore.py:open_for_write():85] open: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/run-9nl6aev6.wandb
2024-05-14 14:36:16,178 DEBUG   SenderThread:930393 [sender.py:send():382] send: header
2024-05-14 14:36:16,178 DEBUG   SenderThread:930393 [sender.py:send():382] send: run
2024-05-14 14:36:16,535 INFO    SenderThread:930393 [dir_watcher.py:__init__():211] watching files in: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files
2024-05-14 14:36:16,535 INFO    SenderThread:930393 [sender.py:_start_run_threads():1136] run started: 9nl6aev6 with start time 1715690176.174411
2024-05-14 14:36:16,550 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: check_version
2024-05-14 14:36:16,550 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: check_version
2024-05-14 14:36:16,612 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: run_start
2024-05-14 14:36:16,641 DEBUG   HandlerThread:930393 [system_info.py:__init__():32] System info init
2024-05-14 14:36:16,641 DEBUG   HandlerThread:930393 [system_info.py:__init__():47] System info init done
2024-05-14 14:36:16,641 INFO    HandlerThread:930393 [system_monitor.py:start():194] Starting system monitor
2024-05-14 14:36:16,641 INFO    SystemMonitor:930393 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-14 14:36:16,642 INFO    HandlerThread:930393 [system_monitor.py:probe():214] Collecting system info
2024-05-14 14:36:16,642 INFO    SystemMonitor:930393 [interfaces.py:start():190] Started cpu monitoring
2024-05-14 14:36:16,643 INFO    SystemMonitor:930393 [interfaces.py:start():190] Started disk monitoring
2024-05-14 14:36:16,644 INFO    SystemMonitor:930393 [interfaces.py:start():190] Started gpu monitoring
2024-05-14 14:36:16,644 INFO    SystemMonitor:930393 [interfaces.py:start():190] Started memory monitoring
2024-05-14 14:36:16,644 INFO    SystemMonitor:930393 [interfaces.py:start():190] Started network monitoring
2024-05-14 14:36:16,702 DEBUG   HandlerThread:930393 [system_info.py:probe():196] Probing system
2024-05-14 14:36:16,707 DEBUG   HandlerThread:930393 [gitlib.py:_init_repo():56] git repository is invalid
2024-05-14 14:36:16,707 DEBUG   HandlerThread:930393 [system_info.py:probe():244] Probing system done
2024-05-14 14:36:16,708 DEBUG   HandlerThread:930393 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.10', 'python': '3.8.5', 'heartbeatAt': '2024-05-14T12:36:16.702602', 'startedAt': '2024-05-14T12:36:16.162695', 'docker': None, 'cuda': None, 'args': ('--model_type', 'gpt2', '--HiTaskType', 'CAUSAL_LM', '--optim', 'adamw_torch', '--deepspeed', 'dsconfig/zero0_config.json', '--model_name_or_path', '/mounts/work/lyk/hierFT/gpt2-l', '--dataset_dir', 'alpaca_data', '--validation_split_percentage', '0.01', '--per_device_train_batch_size', '8', '--per_device_eval_batch_size', '8', '--do_train', '--do_eval', '--seed', '12345', '--fp16', '--tf32', 'true', '--num_train_epochs', '1', '--lr_scheduler_type', 'cosine', '--learning_rate', '2e-4', '--warmup_ratio', '0.03', '--weight_decay', '0.0', '--logging_strategy', 'steps', '--logging_steps', '10', '--save_strategy', 'steps', '--save_total_limit', '3', '--evaluation_strategy', 'steps', '--eval_steps', '100', '--save_steps', '200', '--preprocessing_num_workers', '4', '--max_seq_length', '512', '--output_dir', 'outputs/instruct_tuning/model', '--overwrite_output_dir', '--logging_first_step', 'True', '--torch_dtype', 'float16', '--ddp_find_unused_parameters', 'False', '--load_best_model_at_end', '--hier_tuning', '--group_element', '1', '--optimizer_strategy', 'down2up'), 'state': 'running', 'program': 'examples/instruct_tuning.py', 'codePathLocal': 'examples/instruct_tuning.py', 'codePath': 'examples/instruct_tuning.py', 'host': 'rho1', 'username': 'yongkang', 'executable': '/mounts/work/lyk/anaconda3/envs/torch2/bin/python', 'cpu_count': 32, 'cpu_count_logical': 64, 'cpu_freq': {'current': 1938.6770781249998, 'min': 1500.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3723.98, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3723.983, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3723.375, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2200.0, 'min': 1500.0, 'max': 3000.0}], 'disk': {'/': {'total': 878.1072120666504, 'used': 583.3517189025879}}, 'gpu': 'NVIDIA RTX A6000', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}, {'name': 'NVIDIA RTX A6000', 'memory_total': 51527024640}], 'memory': {'total': 251.73123168945312}}
2024-05-14 14:36:16,708 INFO    HandlerThread:930393 [system_monitor.py:probe():224] Finished collecting system info
2024-05-14 14:36:16,708 INFO    HandlerThread:930393 [system_monitor.py:probe():227] Publishing system info
2024-05-14 14:36:16,708 DEBUG   HandlerThread:930393 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-05-14 14:36:16,709 DEBUG   HandlerThread:930393 [system_info.py:_save_pip():68] Saving pip packages done
2024-05-14 14:36:16,709 DEBUG   HandlerThread:930393 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-05-14 14:36:17,537 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/conda-environment.yaml
2024-05-14 14:36:17,538 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/requirements.txt
2024-05-14 14:36:19,442 DEBUG   HandlerThread:930393 [system_info.py:_save_conda():87] Saving conda packages done
2024-05-14 14:36:19,444 INFO    HandlerThread:930393 [system_monitor.py:probe():229] Finished publishing system info
2024-05-14 14:36:19,452 DEBUG   SenderThread:930393 [sender.py:send():382] send: files
2024-05-14 14:36:19,452 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-05-14 14:36:19,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:36:19,459 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:36:19,461 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:36:19,539 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/conda-environment.yaml
2024-05-14 14:36:19,539 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-metadata.json
2024-05-14 14:36:19,723 DEBUG   SenderThread:930393 [sender.py:send():382] send: telemetry
2024-05-14 14:36:19,723 DEBUG   SenderThread:930393 [sender.py:send():382] send: config
2024-05-14 14:36:19,724 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:36:19,724 DEBUG   SenderThread:930393 [sender.py:send():382] send: telemetry
2024-05-14 14:36:19,724 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:36:19,724 WARNING SenderThread:930393 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-05-14 14:36:19,724 DEBUG   SenderThread:930393 [sender.py:send():382] send: telemetry
2024-05-14 14:36:19,891 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-metadata.json?Expires=1715776579&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QzlBBBLbahtediIBt3Ie3WdbAlOxwGrSlXh8RLb16jYyu4SZLhwQa43HVPqjmblgdpCUg%2B5h3rK6yv4Gc7JF2Dt4K%2B3TUjPQXk3G4C8V0ymuFS032lVi%2Fuo6AdqrmCh7lyt0ymbExqXV3i9v88kj5ZsGMjNRixFG%2FPdQ5bWYoElPJsxhqTcoDxwkDUQp8MRS8RjAyXmvngGQMPy1b5vl59wGyqcaFcuanNXkdRhvh4mP%2Bzr75tj2jXulqhA7LVzn7ApVgGi%2BtHfKaWYIMEX06d18MoSM6Mck8n%2FM%2B6l9fpo1eSmYbSn4fWjQwRv68mb7tKNa16ThYgnnb%2BSuPfkc%2Bg%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-metadata.json?Expires=1715776579&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QzlBBBLbahtediIBt3Ie3WdbAlOxwGrSlXh8RLb16jYyu4SZLhwQa43HVPqjmblgdpCUg%2B5h3rK6yv4Gc7JF2Dt4K%2B3TUjPQXk3G4C8V0ymuFS032lVi%2Fuo6AdqrmCh7lyt0ymbExqXV3i9v88kj5ZsGMjNRixFG%2FPdQ5bWYoElPJsxhqTcoDxwkDUQp8MRS8RjAyXmvngGQMPy1b5vl59wGyqcaFcuanNXkdRhvh4mP%2Bzr75tj2jXulqhA7LVzn7ApVgGi%2BtHfKaWYIMEX06d18MoSM6Mck8n%2FM%2B6l9fpo1eSmYbSn4fWjQwRv68mb7tKNa16ThYgnnb%2BSuPfkc%2Bg%3D%3D
2024-05-14 14:36:19,891 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10133'}
2024-05-14 14:36:19,891 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:36:19,938 ERROR   wandb-upload_0:930393 [upload_job.py:push():134] Failed to upload file: /tmp/tmp8xg99st4wandb/gohh2h2e-wandb-metadata.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-metadata.json?Expires=1715776579&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QzlBBBLbahtediIBt3Ie3WdbAlOxwGrSlXh8RLb16jYyu4SZLhwQa43HVPqjmblgdpCUg%2B5h3rK6yv4Gc7JF2Dt4K%2B3TUjPQXk3G4C8V0ymuFS032lVi%2Fuo6AdqrmCh7lyt0ymbExqXV3i9v88kj5ZsGMjNRixFG%2FPdQ5bWYoElPJsxhqTcoDxwkDUQp8MRS8RjAyXmvngGQMPy1b5vl59wGyqcaFcuanNXkdRhvh4mP%2Bzr75tj2jXulqhA7LVzn7ApVgGi%2BtHfKaWYIMEX06d18MoSM6Mck8n%2FM%2B6l9fpo1eSmYbSn4fWjQwRv68mb7tKNa16ThYgnnb%2BSuPfkc%2Bg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:36:19,960 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp8xg99st4wandb/gohh2h2e-wandb-metadata.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-metadata.json?Expires=1715776579&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QzlBBBLbahtediIBt3Ie3WdbAlOxwGrSlXh8RLb16jYyu4SZLhwQa43HVPqjmblgdpCUg%2B5h3rK6yv4Gc7JF2Dt4K%2B3TUjPQXk3G4C8V0ymuFS032lVi%2Fuo6AdqrmCh7lyt0ymbExqXV3i9v88kj5ZsGMjNRixFG%2FPdQ5bWYoElPJsxhqTcoDxwkDUQp8MRS8RjAyXmvngGQMPy1b5vl59wGyqcaFcuanNXkdRhvh4mP%2Bzr75tj2jXulqhA7LVzn7ApVgGi%2BtHfKaWYIMEX06d18MoSM6Mck8n%2FM%2B6l9fpo1eSmYbSn4fWjQwRv68mb7tKNa16ThYgnnb%2BSuPfkc%2Bg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:36:20,471 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:20,472 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:36:20,473 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:36:20,473 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:36:20,473 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:20,473 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:20,476 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:20,540 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:20,540 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_created():271] file/dir created: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:21,712 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:22,543 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:24,545 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:25,193 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:25,194 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:25,194 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:25,195 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:25,546 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:26,547 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:26,788 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:28,549 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:29,697 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:29,697 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:29,698 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:29,699 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:30,551 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:30,552 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:31,891 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:32,553 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:33,064 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:33,065 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:33,066 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:33,067 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:33,554 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:34,458 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:36:34,459 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:36:34,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:36:34,555 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:36,557 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:36,565 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:36,566 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:36,567 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:36,567 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:37,202 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:37,558 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:38,559 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:40,561 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:41,894 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:41,896 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:41,896 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:41,897 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:42,269 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:42,563 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:42,563 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:44,565 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:45,655 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:45,656 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:45,657 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:45,658 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:46,567 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:46,567 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:47,426 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:48,351 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:48,353 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:48,354 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:48,355 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:48,569 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/config.yaml
2024-05-14 14:36:48,569 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:48,569 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:49,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:36:49,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:36:49,460 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:36:50,571 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:51,888 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:51,889 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:51,889 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:51,890 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:52,572 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:52,573 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:52,920 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:54,574 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:56,455 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:36:56,456 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:36:56,456 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:36:56,457 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:36:56,577 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:36:56,577 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:36:57,976 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:36:58,578 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:00,232 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:00,233 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:00,233 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:00,234 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:00,580 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:00,580 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:02,581 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:02,822 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send():382] send: metric
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:02,825 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:02,826 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:03,057 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:03,582 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:04,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:37:04,459 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:37:04,461 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:37:04,583 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:05,782 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:05,783 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:05,783 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:05,784 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:06,586 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:06,586 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:08,277 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:08,587 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:10,590 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:10,801 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:10,802 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:10,802 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:10,803 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:11,590 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:12,592 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:13,702 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:14,594 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:15,369 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:15,370 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:15,371 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:15,372 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:15,595 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:16,596 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:16,645 DEBUG   SystemMonitor:930393 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-14 14:37:16,646 DEBUG   SenderThread:930393 [sender.py:send():382] send: stats
2024-05-14 14:37:18,598 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:18,845 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:19,212 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:19,213 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:19,213 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:19,214 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:19,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:37:19,459 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:37:19,461 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:37:19,599 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/config.yaml
2024-05-14 14:37:19,599 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:20,600 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:21,918 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:21,918 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:21,919 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:21,920 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:22,601 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:22,602 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:24,551 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:24,604 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:26,606 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:27,414 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:27,415 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:27,415 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:27,416 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:27,607 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:28,608 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:29,894 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:30,610 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:31,999 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:32,000 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:32,000 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:32,001 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:32,612 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:32,612 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:34,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:37:34,459 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:37:34,459 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:37:34,613 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:35,064 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:35,638 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:35,639 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:35,639 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:35,640 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:36,615 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:36,616 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:38,433 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:38,434 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:38,435 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:38,436 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:38,618 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:38,618 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:40,245 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:40,620 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:42,622 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:44,446 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:44,447 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:44,447 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:44,448 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:44,624 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:44,624 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:45,487 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:46,626 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:46,648 DEBUG   SenderThread:930393 [sender.py:send():382] send: stats
2024-05-14 14:37:47,051 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:37:47,051 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:37:47,052 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:37:47,053 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:37:47,626 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:37:48,627 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:50,258 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:37:50,259 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:37:50,259 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:37:50,500 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:37:52,635 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:37:55,356 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: keepalive
2024-05-14 14:37:55,500 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:00,500 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:05,502 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:10,502 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:12,536 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:38:12,536 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:38:12,539 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:38:14,703 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:15,911 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:16,650 DEBUG   SenderThread:930393 [sender.py:send():382] send: stats
2024-05-14 14:38:16,705 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:16,959 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:16,959 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:16,960 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:16,961 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:17,705 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:18,706 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:20,261 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:20,262 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:20,263 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:20,264 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:20,708 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:20,709 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:21,009 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:22,710 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:23,773 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:23,775 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:23,775 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:23,777 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:24,713 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:24,713 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:26,512 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:26,715 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:27,535 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:38:27,536 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:38:27,537 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:38:28,717 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:29,806 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:29,807 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:29,807 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:29,809 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:30,718 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:30,719 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:31,649 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:32,720 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:33,586 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:33,588 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:33,588 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:33,589 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:33,721 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:34,722 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:36,376 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:36,378 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:36,378 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:36,379 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:36,724 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:36,724 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:36,812 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:38,726 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:40,091 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:40,092 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:40,092 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:40,094 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:40,728 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:40,728 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:42,111 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:42,538 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:38:42,539 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:38:42,539 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:38:42,730 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:44,446 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:44,447 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:44,448 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:44,449 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:44,731 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:44,732 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:46,652 DEBUG   SenderThread:930393 [sender.py:send():382] send: stats
2024-05-14 14:38:46,733 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:47,221 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:48,103 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:48,104 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:48,104 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:48,106 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:48,735 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:48,735 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:50,737 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:50,870 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:50,872 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:50,872 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:50,873 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:51,738 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:52,258 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:52,739 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:53,480 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:53,481 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:53,481 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:53,483 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:53,740 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:38:54,741 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:56,743 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:57,375 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:38:57,539 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:38:57,539 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:38:57,539 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:38:57,890 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:38:57,891 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:38:57,891 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:38:57,893 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:38:58,745 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:38:58,745 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:39:00,747 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:02,432 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:39:02,749 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:03,695 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:39:03,697 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:39:03,697 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:39:03,698 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:39:03,750 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:39:04,750 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:06,753 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:06,983 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:39:06,984 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:39:06,984 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:39:06,986 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:39:07,589 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:39:07,753 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:39:08,755 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:09,464 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:39:09,465 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:39:09,466 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:39:09,467 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:39:09,755 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:39:10,756 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:12,538 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-14 14:39:12,539 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: stop_status
2024-05-14 14:39:12,539 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: stop_status
2024-05-14 14:39:12,758 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:12,780 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:39:14,113 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: partial_history
2024-05-14 14:39:14,114 DEBUG   SenderThread:930393 [sender.py:send():382] send: history
2024-05-14 14:39:14,114 DEBUG   SenderThread:930393 [sender.py:send_request():409] send_request: summary_record
2024-05-14 14:39:14,115 INFO    SenderThread:930393 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-05-14 14:39:14,759 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:14,760 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
2024-05-14 14:39:16,654 DEBUG   SenderThread:930393 [sender.py:send():382] send: stats
2024-05-14 14:39:16,761 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:18,655 DEBUG   HandlerThread:930393 [handler.py:handle_request():146] handle_request: status_report
2024-05-14 14:39:18,763 INFO    Thread-12 :930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:21,362 WARNING StreamThr :930393 [internal.py:is_dead():414] Internal process exiting, parent pid 930152 disappeared
2024-05-14 14:39:21,362 ERROR   StreamThr :930393 [internal.py:wandb_internal():152] Internal process shutdown.
2024-05-14 14:39:21,655 INFO    SenderThread:930393 [sender.py:finish():1548] shutting down sender
2024-05-14 14:39:21,656 INFO    HandlerThread:930393 [handler.py:finish():866] shutting down handler
2024-05-14 14:39:21,656 INFO    WriterThread:930393 [datastore.py:close():294] close: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/run-9nl6aev6.wandb
2024-05-14 14:39:21,656 INFO    HandlerThread:930393 [system_monitor.py:finish():203] Stopping system monitor
2024-05-14 14:39:21,656 DEBUG   SystemMonitor:930393 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-05-14 14:39:21,656 DEBUG   SystemMonitor:930393 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-05-14 14:39:21,658 INFO    HandlerThread:930393 [interfaces.py:finish():202] Joined cpu monitor
2024-05-14 14:39:21,659 INFO    HandlerThread:930393 [interfaces.py:finish():202] Joined disk monitor
2024-05-14 14:39:21,660 INFO    HandlerThread:930393 [interfaces.py:finish():202] Joined gpu monitor
2024-05-14 14:39:21,661 INFO    HandlerThread:930393 [interfaces.py:finish():202] Joined memory monitor
2024-05-14 14:39:21,661 INFO    HandlerThread:930393 [interfaces.py:finish():202] Joined network monitor
2024-05-14 14:39:22,438 INFO    SenderThread:930393 [dir_watcher.py:finish():358] shutting down directory watcher
2024-05-14 14:39:22,765 INFO    SenderThread:930393 [dir_watcher.py:_on_file_modified():288] file/dir modified: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
2024-05-14 14:39:22,765 INFO    SenderThread:930393 [dir_watcher.py:finish():388] scan: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files
2024-05-14 14:39:22,766 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json wandb-summary.json
2024-05-14 14:39:22,766 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/requirements.txt requirements.txt
2024-05-14 14:39:22,766 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/conda-environment.yaml conda-environment.yaml
2024-05-14 14:39:22,770 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/config.yaml config.yaml
2024-05-14 14:39:22,773 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-metadata.json wandb-metadata.json
2024-05-14 14:39:22,773 INFO    SenderThread:930393 [dir_watcher.py:finish():402] scan save: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log output.log
2024-05-14 14:39:22,774 INFO    SenderThread:930393 [file_pusher.py:finish():175] shutting down file pusher
2024-05-14 14:39:22,774 INFO    SenderThread:930393 [file_pusher.py:join():181] waiting for file pusher
2024-05-14 14:39:23,017 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-summary.json?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgDCaVK1Z1tUxuGq7MvHymBSWInOByQHoQLcg%2FrvaxPylk3rZLfm2sOXGDsVx4eYn9C82o4Vslmv0rqvsKSWgQPaCbd%2BXvqah%2FaM2Ti0uB6woJTJmyFmKSkfR0ZErXCAN%2BNRctnz5DMTO8IWxI98VC23JahSiZ8OQ27jUWtKcVejwYF5f8RrBRPJ3AQZDV2B42Q05SOYkg3bH1ErAZt98C8%2F2Xcf6ePu8ZDsBBttn2QMWT45KxBlkkzAZNDhaD43UlJ%2BNRZVuwxuJM1tlCBdLOISNK9nQ%2F2e%2FS37vMTxayZlb2c8MF%2Bi2IXFsfoenTKwA2K9AFDSNgjyUia2IssGYA%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-summary.json?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgDCaVK1Z1tUxuGq7MvHymBSWInOByQHoQLcg%2FrvaxPylk3rZLfm2sOXGDsVx4eYn9C82o4Vslmv0rqvsKSWgQPaCbd%2BXvqah%2FaM2Ti0uB6woJTJmyFmKSkfR0ZErXCAN%2BNRctnz5DMTO8IWxI98VC23JahSiZ8OQ27jUWtKcVejwYF5f8RrBRPJ3AQZDV2B42Q05SOYkg3bH1ErAZt98C8%2F2Xcf6ePu8ZDsBBttn2QMWT45KxBlkkzAZNDhaD43UlJ%2BNRZVuwxuJM1tlCBdLOISNK9nQ%2F2e%2FS37vMTxayZlb2c8MF%2Bi2IXFsfoenTKwA2K9AFDSNgjyUia2IssGYA%3D%3D
2024-05-14 14:39:23,017 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '313'}
2024-05-14 14:39:23,017 ERROR   wandb-upload_0:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:39:23,037 ERROR   wandb-upload_0:930393 [upload_job.py:push():134] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-summary.json?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgDCaVK1Z1tUxuGq7MvHymBSWInOByQHoQLcg%2FrvaxPylk3rZLfm2sOXGDsVx4eYn9C82o4Vslmv0rqvsKSWgQPaCbd%2BXvqah%2FaM2Ti0uB6woJTJmyFmKSkfR0ZErXCAN%2BNRctnz5DMTO8IWxI98VC23JahSiZ8OQ27jUWtKcVejwYF5f8RrBRPJ3AQZDV2B42Q05SOYkg3bH1ErAZt98C8%2F2Xcf6ePu8ZDsBBttn2QMWT45KxBlkkzAZNDhaD43UlJ%2BNRZVuwxuJM1tlCBdLOISNK9nQ%2F2e%2FS37vMTxayZlb2c8MF%2Bi2IXFsfoenTKwA2K9AFDSNgjyUia2IssGYA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,058 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/wandb-summary.json
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/wandb-summary.json?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vgDCaVK1Z1tUxuGq7MvHymBSWInOByQHoQLcg%2FrvaxPylk3rZLfm2sOXGDsVx4eYn9C82o4Vslmv0rqvsKSWgQPaCbd%2BXvqah%2FaM2Ti0uB6woJTJmyFmKSkfR0ZErXCAN%2BNRctnz5DMTO8IWxI98VC23JahSiZ8OQ27jUWtKcVejwYF5f8RrBRPJ3AQZDV2B42Q05SOYkg3bH1ErAZt98C8%2F2Xcf6ePu8ZDsBBttn2QMWT45KxBlkkzAZNDhaD43UlJ%2BNRZVuwxuJM1tlCBdLOISNK9nQ%2F2e%2FS37vMTxayZlb2c8MF%2Bi2IXFsfoenTKwA2K9AFDSNgjyUia2IssGYA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,066 ERROR   wandb-upload_1:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/requirements.txt?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D%2FmvVtz6EHre3%2FW7ZbHoyfHM9ZAWzCnJML26WCmwcW8QLNaECluE20FXQp9FP1wp6Vglv1fJw77rfpL1vzjqAYljzjE%2BwALuUhfUsoRKh%2Bp7GUDG5db0i7zOYAjGe%2B%2BBE8ZmesPkoUgfAExkBWUXnPiY3%2F46KzfKosuIuWJ%2BHWcEdEzcgUuKAykLTFur8cvIeMqavh4H0wfsnhHsFGQfxdchoWCRpazhmcSyTHv6HdTwC%2FQrLF1sW%2FTMms4Fn8EgAuZCu3c%2FMgMZuT4KIu4M0wgwo8iEx5fhhSQFMzl%2FVXTe7lAeQx5UfDJZXtZAhuPUcQucMDr1H48uMbNjxYEv4g%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/requirements.txt?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D%2FmvVtz6EHre3%2FW7ZbHoyfHM9ZAWzCnJML26WCmwcW8QLNaECluE20FXQp9FP1wp6Vglv1fJw77rfpL1vzjqAYljzjE%2BwALuUhfUsoRKh%2Bp7GUDG5db0i7zOYAjGe%2B%2BBE8ZmesPkoUgfAExkBWUXnPiY3%2F46KzfKosuIuWJ%2BHWcEdEzcgUuKAykLTFur8cvIeMqavh4H0wfsnhHsFGQfxdchoWCRpazhmcSyTHv6HdTwC%2FQrLF1sW%2FTMms4Fn8EgAuZCu3c%2FMgMZuT4KIu4M0wgwo8iEx5fhhSQFMzl%2FVXTe7lAeQx5UfDJZXtZAhuPUcQucMDr1H48uMbNjxYEv4g%3D%3D
2024-05-14 14:39:23,066 ERROR   wandb-upload_1:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2434'}
2024-05-14 14:39:23,066 ERROR   wandb-upload_1:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:39:23,084 ERROR   wandb-upload_1:930393 [upload_job.py:push():134] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/requirements.txt
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/requirements.txt?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D%2FmvVtz6EHre3%2FW7ZbHoyfHM9ZAWzCnJML26WCmwcW8QLNaECluE20FXQp9FP1wp6Vglv1fJw77rfpL1vzjqAYljzjE%2BwALuUhfUsoRKh%2Bp7GUDG5db0i7zOYAjGe%2B%2BBE8ZmesPkoUgfAExkBWUXnPiY3%2F46KzfKosuIuWJ%2BHWcEdEzcgUuKAykLTFur8cvIeMqavh4H0wfsnhHsFGQfxdchoWCRpazhmcSyTHv6HdTwC%2FQrLF1sW%2FTMms4Fn8EgAuZCu3c%2FMgMZuT4KIu4M0wgwo8iEx5fhhSQFMzl%2FVXTe7lAeQx5UfDJZXtZAhuPUcQucMDr1H48uMbNjxYEv4g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,087 ERROR   wandb-upload_2:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/conda-environment.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fELsqNDf%2BMpz7QuPFJPdxpoxneIL8i%2BUCstK5%2Biig7ZoVvkuI2mf344VUnTb58844c7lnK7PwCLec8lnICSoSbj%2FAcYGLGHMh0zo9fW%2FunC80y786qYcdMTbb08SKEqS8TKm6zVMuNWj%2BnIGuGb8nOljXyyjYVhfL2W%2BQaLdLkzTjIwnPh0wg9oAK3ojoLxj%2FZzl0vDcpMjwDyJFscKsJkAUN0zGF1L%2F7xlgCjICDOX060YY4%2FcpzK69KIFUNb0couywo2Eiyb5uaJALj84RFMWT3c%2BWwpxv8NhsIZNf7qb42awr9PAFOo0i9Iq20D9GV9vLY70tdpoPjUjNAjpNdw%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/conda-environment.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fELsqNDf%2BMpz7QuPFJPdxpoxneIL8i%2BUCstK5%2Biig7ZoVvkuI2mf344VUnTb58844c7lnK7PwCLec8lnICSoSbj%2FAcYGLGHMh0zo9fW%2FunC80y786qYcdMTbb08SKEqS8TKm6zVMuNWj%2BnIGuGb8nOljXyyjYVhfL2W%2BQaLdLkzTjIwnPh0wg9oAK3ojoLxj%2FZzl0vDcpMjwDyJFscKsJkAUN0zGF1L%2F7xlgCjICDOX060YY4%2FcpzK69KIFUNb0couywo2Eiyb5uaJALj84RFMWT3c%2BWwpxv8NhsIZNf7qb42awr9PAFOo0i9Iq20D9GV9vLY70tdpoPjUjNAjpNdw%3D%3D
2024-05-14 14:39:23,087 ERROR   wandb-upload_2:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5415'}
2024-05-14 14:39:23,087 ERROR   wandb-upload_2:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:39:23,107 ERROR   wandb-upload_4:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/output.log?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LMwgjXDQsV8xAfuK8I6%2Fwt9q8fOrX3hu53rOJ3r4GjXZmc7qrSKcBqn6P7F%2FCbXRxhg3Pz%2BsOhDzvggMX4dEw9Ggj1YAtzx1sWkV14js6QhwcJKiix4lx8GhDHAXjN05jhIMsB4kQ24J7qEusyFQlrc2IC21oSLNBO0l092AF6PwfBoTe%2B39tDtIQFLRWTTdUrszQihMlLWjeJwGC6rhD37NGzDHY4JpnNKMmDjg7NZyBOi%2BoM7FAmdGmZfqAKB0gWnUEcudVnKyZhmaUzZc4si9%2FcPTLH5nZPggZop%2B4nP6EIlYYzJieeOb1uIF%2FI9SFitc7Pnc3BoKatS1ZO%2B8rg%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/output.log?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LMwgjXDQsV8xAfuK8I6%2Fwt9q8fOrX3hu53rOJ3r4GjXZmc7qrSKcBqn6P7F%2FCbXRxhg3Pz%2BsOhDzvggMX4dEw9Ggj1YAtzx1sWkV14js6QhwcJKiix4lx8GhDHAXjN05jhIMsB4kQ24J7qEusyFQlrc2IC21oSLNBO0l092AF6PwfBoTe%2B39tDtIQFLRWTTdUrszQihMlLWjeJwGC6rhD37NGzDHY4JpnNKMmDjg7NZyBOi%2BoM7FAmdGmZfqAKB0gWnUEcudVnKyZhmaUzZc4si9%2FcPTLH5nZPggZop%2B4nP6EIlYYzJieeOb1uIF%2FI9SFitc7Pnc3BoKatS1ZO%2B8rg%3D%3D
2024-05-14 14:39:23,107 ERROR   wandb-upload_4:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6041'}
2024-05-14 14:39:23,107 ERROR   wandb-upload_4:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:39:23,120 ERROR   wandb-upload_3:930393 [internal_api.py:upload_file():2761] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/config.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qtPPbDpiw6v0K5RDYF%2BRXc7UFHPKhKCrp7sFz8LEGez1LFp%2FaVVxc0Ua6uGre2Jxpjln3HPEE8C6A0oRJDdUDMxUaAWnLKvMQj4ErtgunjOLp7eg9hFe849yo06aUx1St7SqAKbuJ4CZS%2FKAHKt%2FWBxGegkftD3uOwJTYgy8cGwl%2BfFNLjiGMHoCo5QlUEr3bIJotC7Y9XyRgqbZyQIkIrwd%2BqNR6I2kmkjvN0UDNsoZklRbzmtpAQI%2FM32PGF7KQRdq25Z9IVE17wuO2bgP6CqWm3obfkCLetxb2du3ct9j4n0CD1fp61x5TrP2eX3Xp%2BVcj9tBUL5nHtT8I692AQ%3D%3D: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/config.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qtPPbDpiw6v0K5RDYF%2BRXc7UFHPKhKCrp7sFz8LEGez1LFp%2FaVVxc0Ua6uGre2Jxpjln3HPEE8C6A0oRJDdUDMxUaAWnLKvMQj4ErtgunjOLp7eg9hFe849yo06aUx1St7SqAKbuJ4CZS%2FKAHKt%2FWBxGegkftD3uOwJTYgy8cGwl%2BfFNLjiGMHoCo5QlUEr3bIJotC7Y9XyRgqbZyQIkIrwd%2BqNR6I2kmkjvN0UDNsoZklRbzmtpAQI%2FM32PGF7KQRdq25Z9IVE17wuO2bgP6CqWm3obfkCLetxb2du3ct9j4n0CD1fp61x5TrP2eX3Xp%2BVcj9tBUL5nHtT8I692AQ%3D%3D
2024-05-14 14:39:23,120 ERROR   wandb-upload_3:930393 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10417'}
2024-05-14 14:39:23,120 ERROR   wandb-upload_3:930393 [internal_api.py:upload_file():2765] upload_file response body: b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>"
2024-05-14 14:39:23,155 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/requirements.txt
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/requirements.txt?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=D%2FmvVtz6EHre3%2FW7ZbHoyfHM9ZAWzCnJML26WCmwcW8QLNaECluE20FXQp9FP1wp6Vglv1fJw77rfpL1vzjqAYljzjE%2BwALuUhfUsoRKh%2Bp7GUDG5db0i7zOYAjGe%2B%2BBE8ZmesPkoUgfAExkBWUXnPiY3%2F46KzfKosuIuWJ%2BHWcEdEzcgUuKAykLTFur8cvIeMqavh4H0wfsnhHsFGQfxdchoWCRpazhmcSyTHv6HdTwC%2FQrLF1sW%2FTMms4Fn8EgAuZCu3c%2FMgMZuT4KIu4M0wgwo8iEx5fhhSQFMzl%2FVXTe7lAeQx5UfDJZXtZAhuPUcQucMDr1H48uMbNjxYEv4g%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,155 ERROR   wandb-upload_4:930393 [upload_job.py:push():134] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/output.log?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LMwgjXDQsV8xAfuK8I6%2Fwt9q8fOrX3hu53rOJ3r4GjXZmc7qrSKcBqn6P7F%2FCbXRxhg3Pz%2BsOhDzvggMX4dEw9Ggj1YAtzx1sWkV14js6QhwcJKiix4lx8GhDHAXjN05jhIMsB4kQ24J7qEusyFQlrc2IC21oSLNBO0l092AF6PwfBoTe%2B39tDtIQFLRWTTdUrszQihMlLWjeJwGC6rhD37NGzDHY4JpnNKMmDjg7NZyBOi%2BoM7FAmdGmZfqAKB0gWnUEcudVnKyZhmaUzZc4si9%2FcPTLH5nZPggZop%2B4nP6EIlYYzJieeOb1uIF%2FI9SFitc7Pnc3BoKatS1ZO%2B8rg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,155 ERROR   wandb-upload_2:930393 [upload_job.py:push():134] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/conda-environment.yaml
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/conda-environment.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fELsqNDf%2BMpz7QuPFJPdxpoxneIL8i%2BUCstK5%2Biig7ZoVvkuI2mf344VUnTb58844c7lnK7PwCLec8lnICSoSbj%2FAcYGLGHMh0zo9fW%2FunC80y786qYcdMTbb08SKEqS8TKm6zVMuNWj%2BnIGuGb8nOljXyyjYVhfL2W%2BQaLdLkzTjIwnPh0wg9oAK3ojoLxj%2FZzl0vDcpMjwDyJFscKsJkAUN0zGF1L%2F7xlgCjICDOX060YY4%2FcpzK69KIFUNb0couywo2Eiyb5uaJALj84RFMWT3c%2BWwpxv8NhsIZNf7qb42awr9PAFOo0i9Iq20D9GV9vLY70tdpoPjUjNAjpNdw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,156 ERROR   wandb-upload_3:930393 [upload_job.py:push():134] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/config.yaml
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/config.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qtPPbDpiw6v0K5RDYF%2BRXc7UFHPKhKCrp7sFz8LEGez1LFp%2FaVVxc0Ua6uGre2Jxpjln3HPEE8C6A0oRJDdUDMxUaAWnLKvMQj4ErtgunjOLp7eg9hFe849yo06aUx1St7SqAKbuJ4CZS%2FKAHKt%2FWBxGegkftD3uOwJTYgy8cGwl%2BfFNLjiGMHoCo5QlUEr3bIJotC7Y9XyRgqbZyQIkIrwd%2BqNR6I2kmkjvN0UDNsoZklRbzmtpAQI%2FM32PGF7KQRdq25Z9IVE17wuO2bgP6CqWm3obfkCLetxb2du3ct9j4n0CD1fp61x5TrP2eX3Xp%2BVcj9tBUL5nHtT8I692AQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,215 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/output.log
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/output.log?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LMwgjXDQsV8xAfuK8I6%2Fwt9q8fOrX3hu53rOJ3r4GjXZmc7qrSKcBqn6P7F%2FCbXRxhg3Pz%2BsOhDzvggMX4dEw9Ggj1YAtzx1sWkV14js6QhwcJKiix4lx8GhDHAXjN05jhIMsB4kQ24J7qEusyFQlrc2IC21oSLNBO0l092AF6PwfBoTe%2B39tDtIQFLRWTTdUrszQihMlLWjeJwGC6rhD37NGzDHY4JpnNKMmDjg7NZyBOi%2BoM7FAmdGmZfqAKB0gWnUEcudVnKyZhmaUzZc4si9%2FcPTLH5nZPggZop%2B4nP6EIlYYzJieeOb1uIF%2FI9SFitc7Pnc3BoKatS1ZO%2B8rg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,216 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/conda-environment.yaml
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/conda-environment.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fELsqNDf%2BMpz7QuPFJPdxpoxneIL8i%2BUCstK5%2Biig7ZoVvkuI2mf344VUnTb58844c7lnK7PwCLec8lnICSoSbj%2FAcYGLGHMh0zo9fW%2FunC80y786qYcdMTbb08SKEqS8TKm6zVMuNWj%2BnIGuGb8nOljXyyjYVhfL2W%2BQaLdLkzTjIwnPh0wg9oAK3ojoLxj%2FZzl0vDcpMjwDyJFscKsJkAUN0zGF1L%2F7xlgCjICDOX060YY4%2FcpzK69KIFUNb0couywo2Eiyb5uaJALj84RFMWT3c%2BWwpxv8NhsIZNf7qb42awr9PAFOo0i9Iq20D9GV9vLY70tdpoPjUjNAjpNdw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,216 ERROR   Thread-11 :930393 [step_upload.py:_handle_event():200] Failed to upload file: /nfs/datx/lyk/HiFT/wandb/run-20240514_143616-9nl6aev6/files/config.yaml
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2787, in upload_file
    wandb._sentry.reraise(e)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://storage.googleapis.com/wandb-production.appspot.com/neuzxm/huggingface/9nl6aev6/config.yaml?Expires=1715776762&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qtPPbDpiw6v0K5RDYF%2BRXc7UFHPKhKCrp7sFz8LEGez1LFp%2FaVVxc0Ua6uGre2Jxpjln3HPEE8C6A0oRJDdUDMxUaAWnLKvMQj4ErtgunjOLp7eg9hFe849yo06aUx1St7SqAKbuJ4CZS%2FKAHKt%2FWBxGegkftD3uOwJTYgy8cGwl%2BfFNLjiGMHoCo5QlUEr3bIJotC7Y9XyRgqbZyQIkIrwd%2BqNR6I2kmkjvN0UDNsoZklRbzmtpAQI%2FM32PGF7KQRdq25Z9IVE17wuO2bgP6CqWm3obfkCLetxb2du3ct9j4n0CD1fp61x5TrP2eX3Xp%2BVcj9tBUL5nHtT8I692AQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 125, in push
    self._api.upload_file_retry(
  File "/mounts/work/lyk/anaconda3/envs/torch2/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [403]>
2024-05-14 14:39:23,650 INFO    MainThread:930393 [internal.py:handle_exit():76] Internal process exited
